### ISSUE TITLE
Code for turning referrals logo any other colour is broken

### ISSUE THREAD

**Issue by AditiBhandariTR** [reuters-graphics/graphics-svelte-components#42]
@MinamiFunakoshiTR fixed locally for the Paralympics project: https://github.com/tr/graphics_2022-winter-paralympics-equipment/commit/b250e79db5d2445ca0641981692386b5b0d95dfe

**Comment by hobbes7878** [comment]
Hey, Aditi. Thanks for flagging.

So I noticed in your project, your `@reuters-graphics/graphics-svelte-components` library was only set to `^0.2.0` in [package.json](https://github.com/tr/graphics_2022-winter-paralympics-equipment/blob/master/package.json#L64) (which basically sets a range of allowed versions of the library, in this case anything above 0.2.0) and that according to your yarn.lock file, you had [version `0.2.1` installed](https://github.com/tr/graphics_2022-winter-paralympics-equipment/blob/master/yarn.lock#L1197) (which determines the _exact_ version you're using).

The feature you're looking for came in in `0.2.4`, so you would've needed to upgrade that dependency to get it. You can do that by changing that version number in `package.json` to whatever the latest version of the library is, which you can usually find right on the README for this repo: 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/2772078/158327533-97ba8d31-76cd-4a39-ba01-f96649b623a9.png">

So in this case, changing it to `^0.2.4` and then, of course, running `yarn` to install it will get you that new feature.

Ima close this issue out for now, but if it turns out something else wasn't working for ya, feel free to re-open.
