### ISSUE TITLE
Scroller component flashing transition

### ISSUE THREAD

**Issue by fcage** [reuters-graphics/graphics-svelte-components#73]
Often when we use the scroller component with AI graphics, the slides transition building or layering on the previous. However, the transition follows the pattern that as the previous slide alphas to 0 and the new slide alphas to 1, means that there's a visible, pulsing flash between slides. This is both distracting and confusing because the reader loses focus on what is actually changing because for a few milliseconds everything changes.

Can props be added to adjust the transition behavior, so that previous slides stay visible or we can turn off the fade back to 0 of the previous slide? There are, of course, use cases where we want the previous slide to go to 0, however most of the work we do this is not the case.

You can see it to some degree in the link below, but is more obvious in other projects we've done.
https://graphics.reuters.com/USA-ABORTION/GRAPHIC/zgpomdbeopd/

**Comment by MinamiFunakoshiTR** [comment]
Sorry for the late response. The flashing happened because the `stackBackground` prop was manually set to `false` in the repo for the abortion story. (By default, this prop is set to `true`.)

Here's an explanation of this prop from the [components demo/doc](https://reuters-graphics.github.io/graphics-svelte-components/components/scroller/):

> `stackBackground` determines whether previous background step graphics will stack below the current one.
> - If `true` (default): Background graphics from previous steps will remain visible below the active one, allowing you to stack graphics with transparent backgrounds.
> - If `false`: Only the background graphic from the current step will show and backgrounds from previous steps are hidden.

This explanation is halfway down the doc page, so maybe some people don't know about it. Do you think we should ping the graphics channel to let people know about this prop?

When I changed `stackBackground` to `true` like below, the issue was fixed. Here's the [preview link](https://graphics.thomsonreuters.com/testfiles/2022/sayVuiYXLMK/) with this change.
```
        <Scroller
          steps="{steps}"
          backgroundSize="{block.BackgroundSize}"
          foregroundPosition="{block.ForegroundPosition}"
          id="{block.ID}"
          embedded="{embedded}"
          stackBackground="{true}" // Set this to true to make graphics stack 
        />
```
